"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
format = "$directory$git_branch$git_status$fill$nodejs$python$ruby$rust$golang$java$php$cmd_duration$jobs$line_break$character"

[fill]
symbol = " "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "

[git_status]
disabled = false

[cmd_duration]
min_time = 500
format = "[$duration]($style) "

[nodejs]
format = "[$symbol($version )]($style)"

[python]
format = "[$symbol($version )]($style)"
